window.EIGHTLABO_CONFIG = {
  supabaseUrl: 'https://uksoinulgbchzvvbcezi.supabase.co',
  supabasePublishableKey: 'sb_publishable_fm6TZ6GTN8papKDtKakX9w_O5Vf8Oax',
  serviceUrls: { ACADEMY: 'https://8labo.github.io/8labo-academy.app.demo2/', BIZFIT: 'https://8labo.github.io/bizfit-club.app.demo2/' },
  adminUrls: { PORTAL: 'https://8labo.github.io/8labo.app.demo/staff.html', COMMON: 'https://8labo.github.io/8labo.app.demo/admin.html', EXPORT: 'https://8labo.github.io/8labo.app.demo/data-export.html', ACADEMY: 'https://8labo.github.io/8labo-academy.app.demo2/admin.html', BIZFIT: 'https://8labo.github.io/bizfit-club.app.demo2/admin.html' }
};
(function(){
 const wireServiceLinks=()=>{const urls=window.EIGHTLABO_CONFIG?.serviceUrls;if(!urls)return;document.querySelectorAll('[data-code]').forEach(card=>{const code=card.dataset.code,url=urls[code];if(!url)return;card.setAttribute('role','link');card.setAttribute('tabindex','0');card.setAttribute('aria-label',`${code}を開く`);const open=()=>location.href=url;card.addEventListener('click',open);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}})})};
 const addStaffAdminEntry=async()=>{try{if(!window.supabase)return;const c=window.EIGHTLABO_CONFIG,sb=window.supabase.createClient(c.supabaseUrl,c.supabasePublishableKey),{data:{session}}=await sb.auth.getSession();if(!session)return;const{data:id,error}=await sb.rpc('current_staff_id');if(error||!id)return;const a=document.createElement('a');a.href=c.adminUrls.PORTAL;a.textContent='管理';a.style.cssText='position:fixed;right:12px;bottom:10px;z-index:20;font-size:9px;font-weight:700;color:#9ca3af;text-decoration:none;opacity:.72;padding:5px 7px;border-radius:8px;background:rgba(255,255,255,.78);border:1px solid rgba(229,231,235,.8)';document.body.appendChild(a)}catch(_){}};
 const loadWebsitePhotoEditor=()=>{};
 const loadWebsiteVoiceUI=()=>{const p=location.pathname.split('/').pop()||'';if(!['website-admin.html','website-admin-v2.html'].includes(p))return;const s=document.createElement('script');s.src='website-voice-ui.js?v=1';s.defer=true;document.head.appendChild(s)};
 const loadOfficeAuthUI=()=>{if((location.pathname.split('/').pop()||'')!=='office-accounts.html')return;const s=document.createElement('script');s.src='office-auth-ui.js?v=3';s.defer=true;document.head.appendChild(s)};
 const loadPortalContextUI=()=>{const p=location.pathname.split('/').pop()||'index.html';if(!['','index.html'].includes(p))return;const s=document.createElement('script');s.src='portal-context-ui.js?v=1';s.defer=true;document.head.appendChild(s)};
 const loadStaffPermissionUI=()=>{if((location.pathname.split('/').pop()||'')!=='staff.html')return;const s=document.createElement('script');s.src='staff-permission-ui.js?v=1';s.defer=true;document.head.appendChild(s)};
 const loadShiftResponseUI=()=>{if((location.pathname.split('/').pop()||'')!=='shift-v2.html')return;const s=document.createElement('script');s.src='shift-response-ui-v2.js?v=1';document.body.appendChild(s)};
 const init=()=>{wireServiceLinks();addStaffAdminEntry();loadWebsitePhotoEditor();loadWebsiteVoiceUI();loadOfficeAuthUI();loadPortalContextUI();loadStaffPermissionUI();loadShiftResponseUI()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();