window.EIGHTLABO_CONFIG = {
  supabaseUrl: 'https://uksoinulgbchzvvbcezi.supabase.co',
  supabasePublishableKey: 'sb_publishable_fm6TZ6GTN8papKDtKakX9w_O5Vf8Oax',
  serviceUrls: { ACADEMY: 'https://8labo.github.io/8labo-academy.app.demo2/', BIZFIT: 'https://8labo.github.io/bizfit-club.app.demo2/' },
  adminUrls: { PORTAL: 'https://8labo.github.io/8labo.app.demo/staff.html', COMMON: 'https://8labo.github.io/8labo.app.demo/admin.html', EXPORT: 'https://8labo.github.io/8labo.app.demo/data-export.html', ACADEMY: 'https://8labo.github.io/8labo-academy.app.demo2/admin.html', BIZFIT: 'https://8labo.github.io/bizfit-club.app.demo2/admin.html' }
};
(function(){
 const wireServiceLinks=()=>{const urls=window.EIGHTLABO_CONFIG?.serviceUrls;if(!urls)return;document.querySelectorAll('[data-code]').forEach(card=>{const url=urls[card.dataset.code];if(!url)return;card.setAttribute('role','link');card.setAttribute('tabindex','0');const go=()=>location.href=url;card.addEventListener('click',go);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go()}})})};
 const addStaffAdminEntry=async()=>{try{if(!window.supabase)return;const c=EIGHTLABO_CONFIG,sb=supabase.createClient(c.supabaseUrl,c.supabasePublishableKey),{data:{session}}=await sb.auth.getSession();if(!session)return;const{data:staffId}=await sb.rpc('current_staff_id');if(!staffId)return;const a=document.createElement('a');a.href=c.adminUrls.PORTAL;a.textContent='管理';a.style.cssText='position:fixed;right:12px;bottom:10px;z-index:20;font-size:9px;font-weight:700;color:#9ca3af;text-decoration:none;opacity:.72;padding:5px 7px;border-radius:8px;background:rgba(255,255,255,.78);border:1px solid rgba(229,231,235,.8)';document.body.appendChild(a)}catch(_){}};
 const load=(paths,src)=>{const p=location.pathname.split('/').pop()||'';if(!paths.includes(p))return;const s=document.createElement('script');s.src=src;s.defer=true;document.head.appendChild(s)};
 const loadWebsiteTools=()=>{const p=location.pathname.split('/').pop()||'';if(!['website-admin.html','website-admin-v2.html'].includes(p))return;['photo-editor-v2.js?v=3','photo-brightness.js?v=1','website-voice-ui.js?v=1'].forEach(src=>{const s=document.createElement('script');s.src=src;s.defer=true;document.head.appendChild(s)})};
 const init=()=>{wireServiceLinks();addStaffAdminEntry();loadWebsiteTools();load(['office-accounts.html'],'office-auth-ui.js?v=3');load(['','index.html'],'portal-context-ui.js?v=1');load(['staff.html'],'staff-permission-ui.js?v=1');load(['shift-v2.html'],'shift-response-ui-v2.js?v=1')};
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();